# shellcheck shell=bash
# SPDX-License-Identifier: GPL-2.0-or-later

# Generate a per-game vkBasalt config from a preset or selected effects.
function generateVkbasaltConfig() {
    local _gamePath="$1" _output _status=0
    shift

    _output=$(python3 - "$_gamePath" "$@" <<'PYEOF'
import os
import sys
import tempfile
from pathlib import Path


def fail(message):
    print(f"Could not generate vkBasalt config: {message}", file=sys.stderr)
    raise SystemExit(1)


def read_general_values(path):
    values = {}
    section = ""
    try:
        with path.open(encoding="utf-8-sig") as stream:
            for raw_line in stream:
                line = raw_line.strip()
                if line.startswith("[") and line.endswith("]"):
                    section = line[1:-1].strip().lower()
                elif section == "general" and "=" in line and not line.startswith((";", "#")):
                    key, value = line.split("=", 1)
                    values[key.strip().lower()] = value.strip()
    except (OSError, UnicodeError) as error:
        fail(f"cannot read '{path}': {error}")
    return values


game_path = Path(sys.argv[1]).expanduser()
if not game_path.is_dir():
    fail(f"game directory does not exist: '{game_path}'")
game_path = game_path.resolve()

reshade_ini = game_path / "ReShade.ini"
if not reshade_ini.is_file():
    fail(f"'{reshade_ini}' was not found")

general = read_general_values(reshade_ini)
preset_value = general.get("presetpath", "").strip().strip('"')
if preset_value:
    preset_value = preset_value.replace("\\", os.sep)
    preset_path = Path(preset_value).expanduser()
    if not preset_path.is_absolute():
        preset_path = game_path / preset_path
else:
    preset_path = game_path / "ReShadePreset.ini"
if len(sys.argv) <= 2 and not preset_path.is_file():
    print("__NO_RESHADE_PRESET_FOUND__")
    raise SystemExit(3)

shader_dir = game_path / "ReShade_shaders" / "Merged" / "Shaders"
texture_dir = game_path / "ReShade_shaders" / "Merged" / "Textures"
if not shader_dir.is_dir():
    fail(f"merged ReShade shader directory was not found: '{shader_dir}'")

effect_files = []
seen_files = set()
if len(sys.argv) > 2:
    for selected_path in sys.argv[2:]:
        effect_file = Path(selected_path).resolve()
        if not effect_file.is_file() or effect_file.suffix.lower() != ".fx":
            fail(f"selected effect is not a readable .fx file: '{selected_path}'")
        if effect_file not in seen_files:
            seen_files.add(effect_file)
            effect_files.append(effect_file)
else:
    if not preset_path.is_file():
        fail(f"active ReShade preset was not found: '{preset_path}'")
    techniques = read_general_values(preset_path).get("techniques", "")
    if not techniques:
        fail(f"'{preset_path}' does not list enabled ReShade techniques")
    for technique in techniques.split(","):
        technique = technique.strip()
        if not technique:
            continue
        name, separator, relative_path = technique.partition("@")
        relative_path = relative_path.strip().replace("\\", "/")
        if not separator or not name.strip() or not relative_path.lower().endswith(".fx"):
            fail(f"cannot map enabled technique '{technique}' to a .fx file")
        effect_path = Path(relative_path)
        if effect_path.is_absolute() or ".." in effect_path.parts:
            fail(f"unsafe shader path in enabled technique '{technique}'")
        effect_file = shader_dir / effect_path
        if not effect_file.is_file():
            fail(f"shader file for enabled technique '{technique}' is missing: '{effect_file}'")
        resolved = effect_file.resolve()
        if resolved not in seen_files:
            seen_files.add(resolved)
            effect_files.append(resolved)

if not effect_files:
    fail("no ReShade effects were selected")

lines = [
    "# Generated by ReShadeLinux from ReShade effects.",
    "# vkBasalt loads the listed .fx files; ReShade parameter values are not converted.",
    f"effects = {':'.join(f'reshade_effect_{index:03d}' for index in range(1, len(effect_files) + 1))}",
]
for index, effect_file in enumerate(effect_files, 1):
    lines.append(f"reshade_effect_{index:03d} = {effect_file}")
lines.extend([
    f"reshadeTexturePath = {(game_path / 'ReShade_shaders' / 'Merged' / 'Textures').resolve()}",
    f"reshadeIncludePath = {Path(os.path.commonpath([str(path.parent) for path in effect_files])).resolve()}",
    "",
])

output_path = game_path / "vkBasalt.conf"
generated_marker = "# Generated by ReShadeLinux from ReShade effects."
previous_marker = "# Generated by ReShadeLinux from enabled ReShade preset techniques."
if output_path.exists():
    try:
        with output_path.open(encoding="utf-8") as stream:
            is_generated = stream.readline().rstrip("\r\n") in (generated_marker, previous_marker)
    except (OSError, UnicodeError) as error:
        fail(f"cannot inspect existing config '{output_path}': {error}")
    if not is_generated:
        fail(f"'{output_path}' already exists and is not a ReShadeLinux-generated config; it was left unchanged")
    temporary_path = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="utf-8", dir=game_path, prefix=".vkBasalt.conf.", delete=False
        ) as stream:
            temporary_path = Path(stream.name)
            stream.write("\n".join(lines))
        os.chmod(temporary_path, output_path.stat().st_mode & 0o777)
        os.replace(temporary_path, output_path)
    except OSError as error:
        if temporary_path is not None:
            try:
                temporary_path.unlink()
            except OSError as cleanup_error:
                fail(f"cannot update '{output_path}': {error}; temporary file '{temporary_path}' could not be removed: {cleanup_error}")
        fail(f"cannot update '{output_path}': {error}")
else:
    try:
        descriptor = os.open(output_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644)
    except FileExistsError:
        fail(f"'{output_path}' already exists; it was left unchanged")
    except OSError as error:
        fail(f"cannot create '{output_path}': {error}")

    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write("\n".join(lines))
    except OSError as error:
        try:
            output_path.unlink()
        except OSError as cleanup_error:
            fail(
                f"cannot write '{output_path}': {error}; "
                f"the partial file could not be removed: {cleanup_error}"
            )
        fail(f"cannot write '{output_path}': {error}")

print(output_path)
PYEOF
    ) || _status=$?
    if [[ $_status -eq 3 && $_output == "__NO_RESHADE_PRESET_FOUND__" ]]; then
        _selectInstalledVkbasaltEffects "$_gamePath"
        return $?
    fi
    [[ $_status -eq 0 ]] || {
        [[ -n $_output ]] && printf '%s\n' "$_output"
        return "$_status"
    }
    printf '%s\n' "$_output"
}

# Let users choose installed effects when they do not have a saved ReShade preset.
function _selectInstalledVkbasaltEffects() {
    local _gamePath="$1" _file _relative _result _index _answer _selectedName _listed
    local -a _effects=() _rows=() _selected=() _choices=()

    _gamePath=$(cd -- "$_gamePath" && pwd -P) || {
        printf 'Could not resolve the game directory: %s\n' "$_gamePath" >&2
        return 1
    }
    _listed=$(python3 - "$_gamePath" <<'PYEOF'
import os
import re
import sys
from pathlib import Path

game = Path(sys.argv[1]).resolve()
ini = game / "ReShade.ini"
if not ini.is_file():
    print(f"Could not find ReShade.ini at '{ini}'", file=sys.stderr)
    raise SystemExit(1)

section = ""
search_paths = ""
try:
    with ini.open(encoding="utf-8-sig") as stream:
        for raw_line in stream:
            line = raw_line.strip()
            if line.startswith("[") and line.endswith("]"):
                section = line[1:-1].strip().lower()
            elif section == "general" and "=" in line and not line.startswith((";", "#")):
                key, value = line.split("=", 1)
                if key.strip().lower() == "effectsearchpaths":
                    search_paths = value.strip()
                    break
except (OSError, UnicodeError) as error:
    print(f"Could not read '{ini}': {error}", file=sys.stderr)
    raise SystemExit(1)

effects = set()
for configured_path in search_paths.split(","):
    configured_path = configured_path.strip().strip('"').replace("\\", os.sep)
    if not configured_path or re.match(r"^[A-Za-z]:", configured_path):
        continue
    recursive = configured_path.endswith(os.sep + "**") or configured_path.endswith("**")
    configured_path = configured_path.removesuffix(os.sep + "**").removesuffix("**").rstrip(os.sep)
    root = Path(configured_path).expanduser()
    if not root.is_absolute():
        root = game / root
    if not root.is_dir():
        continue
    candidates = root.rglob("*") if recursive else root.glob("*")
    effects.update(path.resolve() for path in candidates if path.is_file() and path.suffix.lower() == ".fx")

for effect in sorted(effects):
    print(effect)
PYEOF
    ) || return $?
    while IFS= read -r _file; do
        [[ -n $_file ]] && _effects+=("$_file")
    done <<< "$_listed"
    if [[ ${#_effects[@]} -eq 0 ]]; then
        printf 'No installed ReShade .fx effects were found in the configured EffectSearchPaths.\n' >&2
        return 1
    fi

    for ((_index = 0; _index < ${#_effects[@]}; _index++)); do
        _relative=${_effects[$_index]}
        [[ $_relative == "$_gamePath/"* ]] && _relative=${_relative#"$_gamePath"/}
        _rows+=("$((_index + 1))" "$_relative" OFF)
    done

    if [[ $_UI_BACKEND != cli ]]; then
        local _listHeight=${#_effects[@]} _height
        if (( _listHeight > 20 )); then
            _listHeight=20
        fi
        _height=$((_listHeight + 8))
        _result=$(ui_checklist "ReShade - Select vkBasalt Effects" \
            "No ReShade preset was found. Choose installed effects to include in vkBasalt.conf. Parameters may not be supported by vkBasalt." \
            "$_height" 100 "$_listHeight" "${_rows[@]}") || return 1
        _result=${_result//\"/}
        _result=${_result//,/ }
        read -r -a _choices <<< "$_result"
        for _selectedName in "${_choices[@]}"; do
            [[ $_selectedName =~ ^[0-9]+$ ]] || continue
            ((_selectedName > 0 && _selectedName <= ${#_effects[@]})) || continue
            _selected+=("${_effects[$((_selectedName - 1))]}")
        done
    else
        [[ -t 0 ]] || {
            printf 'No ReShade preset was found. Run this command interactively to choose effects.\n' >&2
            return 1
        }
        printf 'No ReShade preset was found. Select installed effects for vkBasalt.conf:\n' >&2
        for ((_index = 0; _index < ${#_effects[@]}; _index++)); do
            _relative=${_effects[$_index]}
            [[ $_relative == "$_gamePath/"* ]] && _relative=${_relative#"$_gamePath"/}
            _answer=$(checkStdin "  [$((_index + 1))] $_relative - include? [y/N]: " "^(y|Y|yes|YES|n|N|no|NO|)$") || return 1
            [[ $_answer =~ ^(y|Y|yes|YES)$ ]] && _selected+=("${_effects[$_index]}")
        done
    fi

    if [[ ${#_selected[@]} -eq 0 ]]; then
        printf 'No effects selected; vkBasalt.conf was not created.\n' >&2
        return 1
    fi
    generateVkbasaltConfig "$_gamePath" "${_selected[@]}"
}
